# Generated by Django 5.0.6 on 2024-11-30 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Groups', '0001_initial'),
        ('Readinglog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='books',
            field=models.ManyToManyField(blank=True, related_name='groups', to='Readinglog.book'),
        ),
    ]
