# Generated by Django 5.0.6 on 2024-12-01 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Groups', '0003_post'),
        ('Readinglog', '0002_book_isbn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='books',
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
        migrations.AddField(
            model_name='group',
            name='books',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='Readinglog.book'),
        ),
    ]
