# Generated by Django 5.0.6 on 2024-12-01 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Groups', '0004_remove_group_books_delete_friend_group_books'),
        ('Readinglog', '0002_book_isbn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='books',
        ),
        migrations.AddField(
            model_name='group',
            name='books',
            field=models.ManyToManyField(blank=True, related_name='groups', to='Readinglog.book'),
        ),
    ]
