# Generated by Django 5.0.6 on 2024-12-01 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Groups', '0005_remove_group_books_group_books'),
        ('Readinglog', '0002_book_isbn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='books',
        ),
        migrations.AddField(
            model_name='group',
            name='books',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='Readinglog.book'),
        ),
    ]
